#!/usr/bin/env python3
"""Collect raw Open-Meteo ensemble responses into a deduplicated archive.

Each fetched API response is stored *verbatim* (the raw JSON) under the data
directory, keyed so that re-fetching an unchanged model run does not create a
duplicate. A new file therefore appears only when the API returns genuinely
new data (typically a fresh model run) — which is exactly what lets CI commit
and push to the ``data`` branch only when there is something new.

Layout::

    <data-dir>/<model>/<lat>_<lon>/<reference-date>_<hash>.json

The 12-character hash is a SHA-256 over the response with volatile metadata
(``generationtime_ms``) stripped out, so byte-for-byte identical forecasts
collapse to a single file regardless of when they were fetched.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys
from dataclasses import dataclass

# Allow running as ``python data/collect.py`` from the repo root: make the
# repository root (where ``meteogram.py`` lives) importable.
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import meteogram  # noqa: E402

# Fields that change on every request and must not affect the dedup key.
VOLATILE_KEYS = {"generationtime_ms"}

README = """\
# Raw forecast data archive

This orphan branch is an append-only archive of **raw Open-Meteo Ensemble API
responses**, collected automatically by the
[`Collect raw forecast data`](../../actions) workflow.

Each file is the unmodified API payload. Files are keyed by content hash so an
unchanged model run is never stored twice; a new file (and a new commit) only
appears when the API returns genuinely new data.

```
<model>/<lat>_<lon>/<reference-date>_<hash>.json
```

Do not edit by hand — it is regenerated by CI.
"""


@dataclass(frozen=True)
class Location:
    latitude: float
    longitude: float
    name: str | None = None


# Points to archive. Mirrors the published site (Berlin) by default; add more
# entries here to grow the archive.
LOCATIONS = [
    Location(52.55, 13.41, "Berlin"),
]


def content_hash(payload: dict) -> str:
    """Stable 12-char digest of ``payload`` with volatile metadata removed."""
    stable = {k: v for k, v in payload.items() if k not in VOLATILE_KEYS}
    blob = json.dumps(stable, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(blob.encode("utf-8")).hexdigest()[:12]


def reference_date(payload: dict) -> str:
    """First forecast timestamp's date, used as a sortable filename prefix."""
    times = payload.get("hourly", {}).get("time") or []
    if times:
        return str(times[0]).split("T")[0]
    return "unknown"


def collect_one(loc: Location, data_dir: str, forecast_days: int) -> str | None:
    """Fetch ``loc`` and archive it. Returns the new path, or ``None`` if the
    content is already present (a duplicate)."""
    payload = meteogram.fetch_raw(loc.latitude, loc.longitude, forecast_days)
    digest = content_hash(payload)

    loc_dir = os.path.join(
        data_dir, meteogram.MODEL, f"{loc.latitude:g}_{loc.longitude:g}"
    )
    os.makedirs(loc_dir, exist_ok=True)

    # Dedup: a file already ending in this content hash means no new data.
    for existing in os.listdir(loc_dir):
        if existing.endswith(f"_{digest}.json"):
            return None

    path = os.path.join(loc_dir, f"{reference_date(payload)}_{digest}.json")
    with open(path, "w") as fh:
        json.dump(payload, fh, indent=2, sort_keys=True)
    return path


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--data-dir", default="data-store",
                        help="directory to write the archive into "
                             "(default: data-store)")
    parser.add_argument("--forecast-days", type=int, default=11,
                        help="forecast length in days (default: 11)")
    args = parser.parse_args()

    os.makedirs(args.data_dir, exist_ok=True)
    readme = os.path.join(args.data_dir, "README.md")
    if not os.path.exists(readme):
        with open(readme, "w") as fh:
            fh.write(README)

    new = 0
    for loc in LOCATIONS:
        where = loc.name or f"{loc.latitude}, {loc.longitude}"
        path = collect_one(loc, args.data_dir, args.forecast_days)
        if path is None:
            print(f"  {where}: no new data (already archived)")
        else:
            new += 1
            print(f"  {where}: archived {os.path.relpath(path, args.data_dir)}")

    print(f"Done: {new} new file(s) across {len(LOCATIONS)} location(s).")


if __name__ == "__main__":
    main()
