#!/usr/bin/env python3
"""Collect raw Open-Meteo ensemble responses into a per-run archive.

Each stored file is the raw API response plus a single added ``model_run_time``
stamp (see :func:`collect_one`), keyed by the run's initialisation time *and* a
hash of its forecast content so each distinct forecast is archived exactly once.
The collector fetches the ensemble every cycle and archives only forecasts whose
*content* is new; the run metadata is read solely to label and key a new file,
never to decide whether to fetch (Open-Meteo's run stamp advances on cycles it
doesn't serve fresh data for, so it drifts out of sync with the data). A new
file — and a new commit — therefore appears only when the forecast genuinely
changes, which is what lets CI push to the ``data`` branch only when there is
something new.

Layout::

    <data-dir>/<model>/<lat>_<lon>/<run-init-time>-<content-hash>.json

``<run-init-time>`` is the run's UTC initialisation time (``YYYYMMDDTHHMMSSZ``),
so files sort chronologically and the most recent one is "the latest run".
``<content-hash>`` fingerprints the forecast data itself (see
:func:`content_hash`), so a run whose data merely duplicates an earlier one —
the model-run stamp can advance without the data changing — is never archived or
plotted twice. Any older ``<run-init-time>.json`` files without a hash are still
read, and are migrated to the content-keyed name on the next collection.
"""
from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import os
import time
from dataclasses import dataclass

import requests

ENSEMBLE_URL = "https://ensemble-api.open-meteo.com/v1/ensemble"
# Per-model static metadata (run timestamps etc.); the forecast payload itself
# carries no run time, so the real initialisation time is read from here.
META_URL = "https://api.open-meteo.com/data/{model}/static/meta.json"

# Time format used for the model-run stamp attached to each payload; matches
# Open-Meteo's own ``hourly.time`` strings (UTC, e.g. ``2026-06-22T12:00``).
RUN_TIME_FORMAT = "%Y-%m-%dT%H:%M"

# How many times to re-fetch the data when a new run lands mid-fetch (see
# ``fetch_raw``); a tiny window, so one retry almost always suffices.
RUN_FETCH_RETRIES = 3

# Per-request resilience: the Open-Meteo endpoints occasionally time out or
# return a transient 5xx, and a run archives several locations in one go (each a
# few HTTP calls), so a single flaky response shouldn't fail the whole job.
# Retry the GET a few times with exponential backoff before giving up.
REQUEST_RETRIES = 4
REQUEST_BACKOFF = 2.0  # seconds; doubled after each failed attempt
REQUEST_TIMEOUT = 60  # seconds per attempt

# Filename key: ``<run-stamp>-<content-hash>``. The run stamp (the run's UTC
# initialisation time, YYYYMMDDTHHMMSSZ) keeps files human-readable and
# chronologically sortable; the content hash makes the archive's *identity* the
# forecast data itself, so a run whose data duplicates an earlier one is never
# stored — or plotted — twice (see ``content_hash``).
STAMP_FORMAT = "%Y%m%dT%H%M%SZ"
CONTENT_HASH_LEN = 12

# Fields excluded from the content hash: the API's per-response timing and the
# run stamp we attach. Everything else (valid times + every member series) is
# the forecast, and is what defines a run's identity.
_VOLATILE_KEYS = ("generationtime_ms", "model_run_time")

README = """\
# Raw forecast data archive

This orphan branch is an archive of **raw Open-Meteo Ensemble API responses**,
collected automatically by the `fetch` job of the site workflow.

Each file is the API payload, plus an added `model_run_time` stamp (the run's
UTC initialisation time). Files are keyed by that run init time *and* a hash of
their forecast content, so each distinct forecast is stored once; a new file
(and a new commit) appears only when a genuinely new run becomes available.

```
<model>/<lat>_<lon>/<run-init-time>-<content-hash>.json
```

The content hash means a run whose data merely duplicates an earlier one (the
model-run stamp can advance without the data changing) is never archived twice.
Any older `<run-init-time>.json` files without a hash are still read, and are
migrated to the content-keyed name on the next collection.

Do not edit by hand — it is regenerated by CI.
"""


@dataclass(frozen=True)
class Model:
    """An Open-Meteo Ensemble API model offered on the site.

    ``id`` is the Ensemble API identifier (the value of the ``models``
    parameter); it also names the model's archive sub-tree
    (``<data-dir>/<id>/...``). ``meta_id`` is the model's directory on the
    static-metadata server, which does *not* always match the API id (e.g. the
    API's ``icon_d2_eps`` is served as ``dwd_icon_d2_eps``). ``label`` is the
    human name shown in figure titles and the site's model selector — a proper
    noun, the same in every language. ``cadence`` is an i18n key ("1h"/"3h"/"6h")
    resolved to a localised "model-native …" phrase by the catalogues, since the
    cadence wording is translated. ``forecast_days`` is the model's maximum
    horizon: requesting more days than a model supports is an API error, so each
    model carries its own (e.g. ICON-D2 only reaches 2 days).
    """
    id: str
    meta_id: str
    label: str
    cadence: str
    forecast_days: int


# Ensemble models to collect and offer on the site, in display order. The first
# is the default selection (and the only one the meteogram CLI uses unless asked
# otherwise). Each archives independently under ``<data-dir>/<id>/...``; add a
# model here to grow the archive and the site's model selector. ``meta_id`` (the
# static-metadata directory) is confirmed against
# ``api.open-meteo.com/data/<meta_id>/static/meta.json`` — it differs from the
# API ``id`` for the GEFS and ICON models.
MODELS = [
    Model("ecmwf_ifs025", "ecmwf_ifs025", "ECMWF IFS 0.25°", "3h", 11),
    Model("ecmwf_aifs025", "ecmwf_aifs025_ensemble", "ECMWF AIFS 0.25°", "6h", 11),
    Model("ncep_gefs025", "ncep_gefs025", "NOAA GEFS 0.25°", "3h", 10),
    Model("icon_eu_eps", "dwd_icon_eu_eps", "DWD ICON-EU EPS", "1h", 5),
    Model("icon_d2_eps", "dwd_icon_d2_eps", "DWD ICON-D2 EPS", "1h", 2),
]

# The site default and the meteogram CLI's fallback model.
DEFAULT_MODEL = MODELS[0]


@dataclass(frozen=True)
class Location:
    latitude: float
    longitude: float
    name: str | None = None


# Points to archive. Each becomes a selectable city on the published site (the
# site renders one figure pair per location); add more entries here to grow the
# archive and the city selector.
LOCATIONS = [
    Location(52.55, 13.41, "Berlin"),
    Location(50.08, 14.44, "Prague"),
    Location(48.81, 14.32, "Český Krumlov"),
    Location(48.15, 17.11, "Bratislava"),
]


def _get(url: str, **kwargs) -> requests.Response:
    """GET ``url`` with a per-attempt timeout, retrying transient failures.

    Network timeouts and 5xx responses from the Open-Meteo endpoints are
    retried with exponential backoff (see ``REQUEST_RETRIES``); the last error
    is re-raised if every attempt fails. Keeps a single flaky response from
    failing a collection run that fetches several locations.
    """
    last_exc: Exception | None = None
    for attempt in range(REQUEST_RETRIES):
        try:
            resp = requests.get(url, timeout=REQUEST_TIMEOUT, **kwargs)
            resp.raise_for_status()
            return resp
        except requests.exceptions.RequestException as exc:
            last_exc = exc
            if attempt < REQUEST_RETRIES - 1:
                time.sleep(REQUEST_BACKOFF * (2 ** attempt))
    raise last_exc  # type: ignore[misc]


def latest_run_time(model: Model = DEFAULT_MODEL) -> dt.datetime:
    """Initialisation time (UTC) of the model's latest available run.

    The Ensemble API response carries no run timestamp — its first step is just
    the start of the returned window (always today 00:00 UTC), the *same* value
    no matter which 00/06/12/18 UTC cycle actually produced the data. The real
    run time lives in the model's static metadata, so a forecast can be keyed
    and labelled by the run that produced it rather than by the window start.
    """
    resp = _get(META_URL.format(model=model.meta_id))
    ts = resp.json()["last_run_initialisation_time"]
    return dt.datetime.fromtimestamp(ts, dt.timezone.utc)


def fetch_data(
    latitude: float,
    longitude: float,
    model: Model = DEFAULT_MODEL,
    forecast_days: int | None = None,
    variable: str = "temperature_2m",
) -> dict:
    """Return the Open-Meteo Ensemble API response as a dict (no run stamp).

    This is the raw forecast only — it does *not* touch the run-metadata
    endpoint. Callers that need the data labelled by its model run add the
    ``model_run_time`` key themselves (see :func:`fetch_raw` and
    :func:`collect_one`), so the collector can decide a forecast is new — by
    content — before spending a metadata request on it.

    ``forecast_days`` defaults to the model's own maximum horizon; a smaller
    explicit value caps it (a larger one would be an API error).
    """
    days = model.forecast_days if forecast_days is None else min(
        forecast_days, model.forecast_days)
    params = {
        "latitude": latitude,
        "longitude": longitude,
        "hourly": variable,
        "models": model.id,
        "temporal_resolution": "native",  # model-native (3-hourly / hourly)
        "forecast_days": days,
        "timezone": "GMT",
    }
    return _get(ENSEMBLE_URL, params=params).json()


def fetch_raw(
    latitude: float,
    longitude: float,
    model: Model = DEFAULT_MODEL,
    forecast_days: int | None = None,
    variable: str = "temperature_2m",
) -> dict:
    """Return the Ensemble response plus an added ``model_run_time`` label.

    The data and run stamp come from two separate endpoints, so a new run
    landing between the requests could mislabel the data. The data fetch is
    *bracketed* by two run reads: if the latest run is unchanged across the
    bracket it provably did not change while the data was in flight, so the data
    belongs to that run; if a run lands mid-flight the reads differ and we retry.
    Used by the one-shot meteogram, which always wants a freshly labelled
    forecast. The archival path (:func:`collect_one`) instead fetches the data
    first and only reads the run stamp once the content proves new.
    """
    for _ in range(RUN_FETCH_RETRIES):
        run_before = latest_run_time(model)
        payload = fetch_data(latitude, longitude, model, forecast_days, variable)
        run_after = latest_run_time(model)
        if run_before == run_after:
            break
    payload["model_run_time"] = run_after.strftime(RUN_TIME_FORMAT)
    return payload


def location_dir(data_dir: str, loc: Location, model: Model = DEFAULT_MODEL) -> str:
    """Directory holding ``loc``'s archived responses for ``model``."""
    return os.path.join(
        data_dir, model.id, f"{loc.latitude:g}_{loc.longitude:g}"
    )


def content_hash(payload: dict) -> str:
    """Stable short fingerprint of a payload's *forecast content*.

    Hashes the response with the volatile and identity-bearing fields removed
    (the API's per-request ``generationtime_ms`` and the ``model_run_time`` we
    attach), so two responses carrying the same forecast hash identically no
    matter what run stamp is on them. This is the archive's real identity:
    identical content is stored — and plotted — once, even when the model-run
    metadata advances without the data changing (the cause of the original
    "3 runs, 2 curves" drift).
    """
    content = {k: v for k, v in payload.items() if k not in _VOLATILE_KEYS}
    blob = json.dumps(content, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(blob.encode()).hexdigest()[:CONTENT_HASH_LEN]


def archive_path(loc_dir: str, run: dt.datetime, digest: str) -> str:
    """Content-keyed archive path: ``<stamp>-<digest>.json``."""
    return os.path.join(loc_dir, f"{run.strftime(STAMP_FORMAT)}-{digest}.json")


def _run_stamp(name: str) -> str:
    """Run-init-time stamp embedded in archive file ``name``."""
    return name[: -len(".json")].split("-", 1)[0]


def is_run_file(name: str) -> bool:
    """True if ``name`` is a run archive file.

    Accepts both the content-keyed form ``<stamp>-<hash>.json`` and the older
    ``<stamp>.json`` form (still present on the data branch until the legacy
    files are cleaned up), so reads stay tolerant during the migration.
    """
    if not name.endswith(".json"):
        return False
    try:
        dt.datetime.strptime(_run_stamp(name), STAMP_FORMAT)
    except ValueError:
        return False
    return True


def _is_legacy_run_file(name: str) -> bool:
    """True only for the pre-content-hash ``<stamp>.json`` archive form."""
    if not name.endswith(".json"):
        return False
    try:
        dt.datetime.strptime(name[: -len(".json")], STAMP_FORMAT)
    except ValueError:
        return False
    return True


def _content_archived(loc_dir: str, digest: str) -> bool:
    """True if a content-keyed file for ``digest`` already exists."""
    if not os.path.isdir(loc_dir):
        return False
    suffix = f"-{digest}.json"
    return any(n.endswith(suffix) and is_run_file(n)
               for n in os.listdir(loc_dir))


def latest_file(data_dir: str, loc: Location,
                model: Model = DEFAULT_MODEL) -> str | None:
    """Path to the latest-run archive file for ``loc``/``model`` (or ``None``).

    Files are named by run init time, so the lexicographically last one is the
    most recent run.
    """
    d = location_dir(data_dir, loc, model)
    if not os.path.isdir(d):
        return None
    files = sorted(f for f in os.listdir(d) if is_run_file(f))
    return os.path.join(d, files[-1]) if files else None


def load_latest(data_dir: str, loc: Location,
                model: Model = DEFAULT_MODEL) -> dict:
    """Load the latest-run raw payload for ``loc``/``model``."""
    path = latest_file(data_dir, loc, model)
    if path is None:
        raise FileNotFoundError(
            f"no archived {model.id} data for {loc.latitude}, "
            f"{loc.longitude} in {data_dir}"
        )
    with open(path) as fh:
        return json.load(fh)


def load_all(data_dir: str, loc: Location,
             model: Model = DEFAULT_MODEL) -> list[dict]:
    """Load every archived run for ``loc`` as content-distinct payloads, oldest first.

    Files are keyed by run init time, so sorting by name yields chronological
    order. Payloads with identical forecast content (see :func:`content_hash`)
    are collapsed to their earliest run, so a model-run stamp that advanced
    without the data changing — or a legacy file kept alongside its content-keyed
    copy — contributes a single run rather than a duplicate curve. Returns an
    empty list when nothing is archived yet.
    """
    d = location_dir(data_dir, loc, model)
    if not os.path.isdir(d):
        return []
    payloads = []
    seen: set[str] = set()
    for name in sorted(f for f in os.listdir(d) if is_run_file(f)):
        with open(os.path.join(d, name)) as fh:
            payload = json.load(fh)
        digest = content_hash(payload)
        if digest in seen:
            continue
        seen.add(digest)
        payloads.append(payload)
    return payloads


def _prune_legacy(loc_dir: str) -> None:
    """Drop pre-init-time-keyed archive files (one-time key migration).

    Older files were keyed ``<fetched-at>_<hash>.json``; left in place they
    would sort *after* the new ``<run-init-time>.json`` files and shadow the
    latest run. Only non-run-keyed ``.json`` files are removed. A no-op for a
    not-yet-created location (e.g. a freshly added model's first collection).
    """
    if not os.path.isdir(loc_dir):
        return
    for name in os.listdir(loc_dir):
        if name.endswith(".json") and not is_run_file(name):
            os.remove(os.path.join(loc_dir, name))


def _migrate_keys(loc_dir: str) -> None:
    """Convert legacy ``<stamp>.json`` archives to content-keyed names.

    Each legacy file is rewritten under its ``<stamp>-<hash>.json`` name and the
    bare original is removed. Working oldest-first, a legacy file whose content
    already has a content-keyed copy is dropped without writing another, so a
    duplicated forecast collapses to a single content-keyed archive under its
    earliest run stamp. A no-op once every file is content-keyed.
    """
    if not os.path.isdir(loc_dir):
        return
    for name in sorted(n for n in os.listdir(loc_dir)
                       if _is_legacy_run_file(n)):
        path = os.path.join(loc_dir, name)
        with open(path) as fh:
            payload = json.load(fh)
        digest = content_hash(payload)
        # Write the content-keyed form unless this forecast is already filed
        # (e.g. an earlier run carrying identical data), then drop the bare file.
        if not _content_archived(loc_dir, digest):
            run = dt.datetime.strptime(name[: -len(".json")], STAMP_FORMAT)
            with open(archive_path(loc_dir, run, digest), "w") as fh:
                json.dump(payload, fh, indent=2, sort_keys=True)
        os.remove(path)


def collect_one(loc: Location, data_dir: str, model: Model = DEFAULT_MODEL,
                forecast_days: int | None = None) -> str | None:
    """Archive ``loc``'s latest ``model`` forecast, if not already stored.

    The data is the source of truth: the ensemble is fetched first, and only a
    forecast whose *content* is new (by :func:`content_hash`) is archived. The
    model-run metadata is read **only then**, to label and key the file — never
    to decide whether to fetch. This keeps the run stamp out of the novelty
    decision, because Open-Meteo's run metadata advances on cycles it doesn't
    serve fresh ensemble data for (the shorter 06/18 UTC runs), so the stamp
    drifts out of sync with the data actually returned. Returns the new path, or
    ``None`` when the forecast was already archived.
    """
    loc_dir = location_dir(data_dir, loc, model)
    _migrate_keys(loc_dir)
    _prune_legacy(loc_dir)

    payload = fetch_data(loc.latitude, loc.longitude, model, forecast_days)
    digest = content_hash(payload)
    # Nothing new to store — and, deliberately, no run-metadata request: the
    # stamp is fetched only after a fresh forecast proves new.
    if _content_archived(loc_dir, digest):
        return None

    run = latest_run_time(model)
    payload["model_run_time"] = run.strftime(RUN_TIME_FORMAT)
    path = archive_path(loc_dir, run, digest)
    os.makedirs(loc_dir, exist_ok=True)
    with open(path, "w") as fh:
        json.dump(payload, fh, indent=2, sort_keys=True)
    return path


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--data-dir", default="data-store",
                        help="directory to write the archive into "
                             "(default: data-store)")
    parser.add_argument("--forecast-days", type=int, default=None,
                        help="cap forecast length in days for every model "
                             "(default: each model's own maximum horizon)")
    args = parser.parse_args()

    os.makedirs(args.data_dir, exist_ok=True)
    readme = os.path.join(args.data_dir, "README.md")
    if not os.path.exists(readme):
        with open(readme, "w") as fh:
            fh.write(README)

    new = 0
    for model in MODELS:
        print(f"{model.id}:")
        for loc in LOCATIONS:
            where = loc.name or f"{loc.latitude}, {loc.longitude}"
            path = collect_one(loc, args.data_dir, model, args.forecast_days)
            if path is None:
                print(f"  {where}: latest run already archived; nothing to fetch")
            else:
                new += 1
                print(f"  {where}: archived "
                      f"{os.path.relpath(path, args.data_dir)}")

    print(f"Done: {new} new run(s) across {len(LOCATIONS)} location(s) "
          f"× {len(MODELS)} model(s).")


if __name__ == "__main__":
    main()
