#!/usr/bin/env python3
"""Collect raw Open-Meteo ensemble responses into a per-run archive.

Each stored file is the raw API response plus a single added ``model_run_time``
stamp (see :func:`fetch_raw`), keyed by the model run's initialisation time so a
run is archived exactly once. The collector reads the model metadata first and
downloads the ensemble only when the latest run is not already stored, so a new
file (and a new commit) appears only when a genuinely new run is available —
which is what lets CI push to the ``data`` branch only when there is something
new.

Layout::

    <data-dir>/<model>/<lat>_<lon>/<run-init-time>.json

``<run-init-time>`` is the run's UTC initialisation time (``YYYYMMDDTHHMMSSZ``),
so files sort chronologically and the most recent one is "the latest run".
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import os
from dataclasses import dataclass

import requests

ENSEMBLE_URL = "https://ensemble-api.open-meteo.com/v1/ensemble"
# Per-model static metadata (run timestamps etc.); the forecast payload itself
# carries no run time, so the real initialisation time is read from here.
META_URL = "https://api.open-meteo.com/data/{model}/static/meta.json"
MODEL = "ecmwf_ifs025"

# Time format used for the model-run stamp attached to each payload; matches
# Open-Meteo's own ``hourly.time`` strings (UTC, e.g. ``2026-06-22T12:00``).
RUN_TIME_FORMAT = "%Y-%m-%dT%H:%M"

# How many times to re-fetch the data when a new run lands mid-fetch (see
# ``fetch_raw``); a tiny window, so one retry almost always suffices.
RUN_FETCH_RETRIES = 3

# Filename key: the model run's UTC initialisation time, YYYYMMDDTHHMMSSZ.
STAMP_FORMAT = "%Y%m%dT%H%M%SZ"

README = """\
# Raw forecast data archive

This orphan branch is an archive of **raw Open-Meteo Ensemble API responses**,
collected automatically by the `fetch` job of the site workflow.

Each file is the API payload, plus an added `model_run_time` stamp (the run's
UTC initialisation time). Files are keyed by that run init time, so each model
run is stored exactly once; a new file (and a new commit) appears only when a
new run becomes available.

```
<model>/<lat>_<lon>/<run-init-time>.json
```

Do not edit by hand — it is regenerated by CI.
"""


@dataclass(frozen=True)
class Location:
    latitude: float
    longitude: float
    name: str | None = None


# Points to archive. Each becomes a selectable city on the published site (the
# site renders one figure pair per location); add more entries here to grow the
# archive and the city selector.
LOCATIONS = [
    Location(52.55, 13.41, "Berlin"),
    Location(50.08, 14.44, "Prague"),
    Location(48.81, 14.32, "Český Krumlov"),
    Location(48.15, 17.11, "Bratislava"),
]


def latest_run_time(model: str = MODEL) -> dt.datetime:
    """Initialisation time (UTC) of the model's latest available run.

    The Ensemble API response carries no run timestamp — its first step is just
    the start of the returned window (always today 00:00 UTC), the *same* value
    no matter which 00/06/12/18 UTC cycle actually produced the data. The real
    run time lives in the model's static metadata, so a forecast can be keyed
    and labelled by the run that produced it rather than by the window start.
    """
    resp = requests.get(META_URL.format(model=model), timeout=60)
    resp.raise_for_status()
    ts = resp.json()["last_run_initialisation_time"]
    return dt.datetime.fromtimestamp(ts, dt.timezone.utc)


def fetch_raw(
    latitude: float,
    longitude: float,
    forecast_days: int = 11,
    variable: str = "temperature_2m",
) -> dict:
    """Return the Open-Meteo Ensemble API response as a dict.

    The payload is the API response verbatim, plus a single added
    ``model_run_time`` key (the latest run's UTC initialisation time, from
    :func:`latest_run_time`) so the forecast can be keyed and labelled by its
    actual run rather than the window start.

    The run stamp and the data come from two separate endpoints, so a new run
    landing between the two requests could mislabel the data. To avoid that, the
    data fetch is *bracketed* by two run reads: if the latest run is unchanged
    across the bracket, it provably did not change while the data was in flight,
    so the data belongs to that run. If a run lands mid-flight the reads differ
    and we retry; the rare case where retries are exhausted self-heals on the
    next collection cycle.
    """
    params = {
        "latitude": latitude,
        "longitude": longitude,
        "hourly": variable,
        "models": MODEL,
        "temporal_resolution": "native",  # 3-hourly for ECMWF IFS ENS
        "forecast_days": forecast_days,
        "timezone": "GMT",
    }
    for _ in range(RUN_FETCH_RETRIES):
        run_before = latest_run_time()
        resp = requests.get(ENSEMBLE_URL, params=params, timeout=60)
        resp.raise_for_status()
        payload = resp.json()
        run_after = latest_run_time()
        if run_before == run_after:
            break
    payload["model_run_time"] = run_after.strftime(RUN_TIME_FORMAT)
    return payload


def location_dir(data_dir: str, loc: Location) -> str:
    """Directory holding ``loc``'s archived responses."""
    return os.path.join(
        data_dir, MODEL, f"{loc.latitude:g}_{loc.longitude:g}"
    )


def run_path(loc_dir: str, run: dt.datetime) -> str:
    """Archive path for ``run``, keyed by its UTC initialisation time."""
    return os.path.join(loc_dir, run.strftime(STAMP_FORMAT) + ".json")


def is_run_file(name: str) -> bool:
    """True if ``name`` is an init-time-keyed archive file (``<stamp>.json``)."""
    if not name.endswith(".json"):
        return False
    try:
        dt.datetime.strptime(name[: -len(".json")], STAMP_FORMAT)
    except ValueError:
        return False
    return True


def latest_file(data_dir: str, loc: Location) -> str | None:
    """Path to the latest-run archive file for ``loc`` (or ``None``).

    Files are named by run init time, so the lexicographically last one is the
    most recent run.
    """
    d = location_dir(data_dir, loc)
    if not os.path.isdir(d):
        return None
    files = sorted(f for f in os.listdir(d) if is_run_file(f))
    return os.path.join(d, files[-1]) if files else None


def load_latest(data_dir: str, loc: Location) -> dict:
    """Load the latest-run raw payload for ``loc``."""
    path = latest_file(data_dir, loc)
    if path is None:
        raise FileNotFoundError(
            f"no archived data for {loc.latitude}, {loc.longitude} in {data_dir}"
        )
    with open(path) as fh:
        return json.load(fh)


def load_all(data_dir: str, loc: Location) -> list[dict]:
    """Load every archived run for ``loc``, oldest run first.

    Files are keyed by run init time, so sorting by name yields chronological
    order. Returns an empty list when nothing is archived yet.
    """
    d = location_dir(data_dir, loc)
    if not os.path.isdir(d):
        return []
    payloads = []
    for name in sorted(f for f in os.listdir(d) if is_run_file(f)):
        with open(os.path.join(d, name)) as fh:
            payloads.append(json.load(fh))
    return payloads


def _prune_legacy(loc_dir: str) -> None:
    """Drop pre-init-time-keyed archive files (one-time key migration).

    Older files were keyed ``<fetched-at>_<hash>.json``; left in place they
    would sort *after* the new ``<run-init-time>.json`` files and shadow the
    latest run. Only non-run-keyed ``.json`` files are removed.
    """
    for name in os.listdir(loc_dir):
        if name.endswith(".json") and not is_run_file(name):
            os.remove(os.path.join(loc_dir, name))


def collect_one(loc: Location, data_dir: str, forecast_days: int) -> str | None:
    """Archive ``loc``'s latest model run, if not already stored.

    Gated on the model metadata: the latest run's initialisation time is read
    first and the (expensive) ensemble download is skipped entirely when that
    run is already archived. Returns the new path, or ``None`` when there was
    nothing new to fetch.
    """
    loc_dir = location_dir(data_dir, loc)

    # Metadata gate: don't download the ensemble if the latest run is already
    # here. fetch_raw re-confirms the run, so this is a pure cost-saver.
    if os.path.exists(run_path(loc_dir, latest_run_time())):
        return None

    payload = fetch_raw(loc.latitude, loc.longitude, forecast_days)
    # The bracketed run may have advanced past the gate's read; key by the run
    # fetch_raw actually observed.
    run = dt.datetime.fromisoformat(payload["model_run_time"])
    path = run_path(loc_dir, run)
    if os.path.exists(path):
        return None

    os.makedirs(loc_dir, exist_ok=True)
    with open(path, "w") as fh:
        json.dump(payload, fh, indent=2, sort_keys=True)
    _prune_legacy(loc_dir)
    return path


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--data-dir", default="data-store",
                        help="directory to write the archive into "
                             "(default: data-store)")
    parser.add_argument("--forecast-days", type=int, default=11,
                        help="forecast length in days (default: 11)")
    args = parser.parse_args()

    os.makedirs(args.data_dir, exist_ok=True)
    readme = os.path.join(args.data_dir, "README.md")
    if not os.path.exists(readme):
        with open(readme, "w") as fh:
            fh.write(README)

    new = 0
    for loc in LOCATIONS:
        where = loc.name or f"{loc.latitude}, {loc.longitude}"
        path = collect_one(loc, args.data_dir, args.forecast_days)
        if path is None:
            print(f"  {where}: latest run already archived; nothing to fetch")
        else:
            new += 1
            print(f"  {where}: archived {os.path.relpath(path, args.data_dir)}")

    print(f"Done: {new} new run(s) across {len(LOCATIONS)} location(s).")


if __name__ == "__main__":
    main()
